export const FREE_TRIAL_QUOTA = 3;

export const PLANS = {
  FREE: {
    name: "Essai gratuit",
    price: 0,
    maxUses: 3,
    maxVariants: 3,
    maxFileSize: 50 * 1024 * 1024,
    features: ["3 uniquifications gratuites", "3 variantes max", "Mode Normal uniquement"],
    modes: ["normal"],
    scraper: false,
    scraperLimit: 0,
    scheduler: false,
    apiAccess: false,
    retentionHours: 6,
    isPaid: false,
  },
  STARTER: {
    name: "Starter",
    price: 29,
    paddlePriceId: process.env.PADDLE_STARTER_PRICE_ID ?? "",
    paddlePriceIdYearly: process.env.PADDLE_STARTER_YEARLY_PRICE_ID ?? "",
    filesPerMonth: 200,
    maxVariants: 10,
    maxFileSize: 200 * 1024 * 1024,
    features: [
      "200 fichiers/mois",
      "10 variantes max",
      "Mode Normal + Double Process",
      "IG Scraper",
      "Support email",
    ],
    modes: ["normal", "double"],
    scraper: true,
    scraperLimit: 500,
    scheduler: false,
    apiAccess: false,
    retentionHours: 24,
    isPaid: true,
  },
  PRO: {
    name: "Pro",
    price: 79,
    paddlePriceId: process.env.PADDLE_PRO_PRICE_ID ?? "",
    paddlePriceIdYearly: process.env.PADDLE_PRO_YEARLY_PRICE_ID ?? "",
    filesPerMonth: 1000,
    maxVariants: 50,
    maxFileSize: 500 * 1024 * 1024,
    features: [
      "1000 fichiers/mois",
      "50 variantes max",
      "Mode Stealth",
      "IG + TikTok Scraper",
      "Scheduler automatique",
      "API access",
      "Support prioritaire",
    ],
    modes: ["normal", "double", "stealth"],
    scraper: true,
    scraperLimit: 5000,
    scheduler: true,
    apiAccess: true,
    retentionHours: 48,
    isPaid: true,
  },
  AGENCY: {
    name: "Agency",
    price: 199,
    paddlePriceId: process.env.PADDLE_AGENCY_PRICE_ID ?? "",
    paddlePriceIdYearly: process.env.PADDLE_AGENCY_YEARLY_PRICE_ID ?? "",
    filesPerMonth: -1,
    maxVariants: 100,
    maxFileSize: 1024 * 1024 * 1024,
    features: [
      "Fichiers illimités",
      "100 variantes max",
      "Tous les modes",
      "Scraper illimité",
      "Scheduler illimité",
      "API illimitée",
      "Support Telegram dédié",
      "5 seats (multi-utilisateur)",
    ],
    modes: ["normal", "double", "stealth"],
    scraper: true,
    scraperLimit: -1,
    scheduler: true,
    apiAccess: true,
    retentionHours: 72,
    seats: 5,
    isPaid: true,
  },
} as const;

export type PlanKey = keyof typeof PLANS;
